swagger: "2.0"
info:
  description: "Get Account's data"
  version: "1.0.0"
  title: "Account Information"
host: "127.0.0.1"
basePath: "/v1"
schemes:
- "http"
paths:
  /statistics:
    get:
      description: "Get Account Statistics"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/AccountStatisticsModel"
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponseModel'
        500:
          description: Internal Error
          schema:
            $ref: '#/definitions/ErrorResponseModel'

definitions:
  AccountModel:
    type: object
    properties:
      id:
        type: string
      username:
        type: string
      gender:
        type: string
      age:
        type: number
  AccountStatisticsModel:
    type: object
    properties:
      numberOfPeople:
        type: number
      totalOfAge:
        type: number
      avgAgeOfPeople:
        type: number
  ErrorResponseModel:
    type: object
    properties:
      ErrorMessage:
        type: string